# Generated by Django 5.0.3 on 2024-03-09 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('lançamento', models.CharField(max_length=10)),
                ('diretor', models.CharField(max_length=50)),
                ('sinopse', models.CharField(max_length=255)),
                ('nota', models.CharField(max_length=10)),
                ('comentario', models.CharField(max_length=255)),
                ('create_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
