# Generated by Django 5.0.3 on 2024-03-09 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_moviemanager', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movies',
            new_name='MovieAnalysis',
        ),
    ]
