# Generated by Django 5.0.3 on 2024-03-09 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_moviemanager', '0002_rename_movies_movieanalysis'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movieanalysis',
            old_name='lançamento',
            new_name='lancamento',
        ),
    ]
